### ISSUE TITLE
docs are not very rich...

### ISSUE THREAD

**Issue by mgenev** [hapijs/rejoice#48]
I'm not seeing a whole lot on how to configure the rejoice server, In addition, I want to add more data to the config, but when I try to place my data key somewhere I keep getting things like: 

```
 Error: Invalid server options {
  "load": {
    "sampleInterval": 1000
  },
  "remoteAPI" [1]: "https://xxxsss.api.xxxsss.com/v1/xxxxxsss"
}
```

or `Invalid manifest`

**Comment by lloydbenson** [comment]
Rejoice heavily relies on glue: https://github.com/hapijs/glue.  It is the same manifest this supports so feel free to look over there and see if it helps.  Typically your configuration would go into a hapi plugin and be passed down that way.  The error is indeed correct that it is in invalid spot to put just any random variable.  That being said I'll take a PR to improve the documentation but chances are you'd want to fix it at glue since this is mostly a cli tool wrapper around glue manifests.
